### ISSUE TITLE
“FileName must be specified” issue

### ISSUE THREAD

**Issue by foxet** [NIRALUser/auto_EACSF#15]
Thankyou for your sofware ,but some issue happen when it was running
The software was ran on MAC apple m2

<img width="991" alt="图片" src="https://github.com/NIRALUser/auto_EACSF/assets/1968438/ada84299-3981-4edb-8b7e-e84f29b9cf84">

<img width="801" alt="图片" src="https://github.com/NIRALUser/auto_EACSF/assets/1968438/a15844ad-5aa3-4ed9-9cdb-9afb3001ef36">

<img width="1013" alt="图片" src="https://github.com/NIRALUser/auto_EACSF/assets/1968438/9d7ae671-bb06-48a9-9dc3-fa7204ae8002">

<img width="1039" alt="图片" src="https://github.com/NIRALUser/auto_EACSF/assets/1968438/eaf17038-8786-49eb-8564-983e8d8cf174">
<img width="990" alt="图片" src="https://github.com/NIRALUser/auto_EACSF/assets/1968438/07451efe-2312-4d8a-8f9a-4a76f15d54a6">
<img width="1065" alt="图片" src="https://github.com/NIRALUser/auto_EACSF/assets/1968438/e3b50e20-e46f-467e-b1d2-3935348504f9">

the error message as follow:

<img width="980" alt="图片" src="https://github.com/NIRALUser/auto_EACSF/assets/1968438/c1c6d376-056f-439c-b677-4b253b2b4b00">

libc++abi: terminating due to uncaught exception of type itk::ImageFileReaderException: /Users/juan/UNC/src/auto_EACSF-build/ITKv4-install/include/ITK-4.13/itkImageFileReader.hxx:87:
FileName must be specified

ITK exception caught in main

itk::ImageFileReaderException (0x600000f38470)
Location: "unknown" 
File: /Users/juan/UNC/src/auto_EACSF-build/ITKv4-install/include/ITK-4.13/itkImageFileReader.hxx
Line: 143
Description:  Could not create IO object for reading file /Users/foxet/Documents/zhanghong/output/RigidRegistration/P001_stx.nrrd
The file doesn't exist. 
Filename = /Users/foxet/Documents/zhanghong/output/RigidRegistration/P001_stx.nrrd

Error: ipGetArgument: argument value of option "-majorityVoting" is missing!

libc++abi: terminating due to uncaught exception of type itk::ImageFileReaderException: /Users/juan/UNC/src/auto_EACSF-build/ITKv4-install/include/ITK-4.13/itkImageFileReader.hxx:143:
 Could not create IO object for reading file /Users/foxet/Documents/zhanghong/output/SkullStripping/P001_stx_weightedMajority.nii.gz
The file doesn't exist. 
Filename = /Users/foxet/Documents/zhanghong/output/SkullStripping/P001_stx_weightedMajority.nii.gz

libc++abi: terminating due to uncaught exception of type itk::ImageFileReaderException: /Users/juan/UNC/src/auto_EACSF-build/ITKv4-install/include/ITK-4.13/itkImageFileReader.hxx:143:
 Could not create IO object for reading file /Users/foxet/Documents/zhanghong/output/SkullStripping/P001_stx_weightedMajority.nii.gz
The file doesn't exist. 
Filename = /Users/foxet/Documents/zhanghong/output/SkullStripping/P001_stx_weightedMajority.nii.gz

libc++abi: terminating due to uncaught exception of type itk::ImageFileReaderException: /Users/juan/UNC/src/auto_EACSF-build/ITKv4-install/include/ITK-4.13/itkImageFileReader.hxx:143:
 Could not create IO object for reading file /Users/foxet/Documents/zhanghong/output/SkullStripping/P001_stx_weightedMajority.nii.gz
The file doesn't exist. 
Filename = /Users/foxet/Documents/zhanghong/output/SkullStripping/P001_stx_weightedMajority.nii.gz

libc++abi: terminating due to uncaught exception of type itk::ImageFileReaderException: /Users/juan/UNC/src/auto_EACSF-build/ITKv4-install/include/ITK-4.13/itkImageFileReader.hxx:143:
 Could not create IO object for reading file /Users/foxet/Documents/zhanghong/output/SkullStripping/P001_stx_stripped.nrrd
The file doesn't exist. 
Filename = /Users/foxet/Documents/zhanghong/output/SkullStripping/P001_stx_stripped.nrrd

Exception caught in ANTS: 
/Users/juan/UNC/src/auto_EACSF-build/ITKv4-install/include/ITK-4.13/itkImageFileReader.hxx:143:
 Could not create IO object for reading file /Users/foxet/Documents/zhanghong/output/SkullStripping/P001_stx_stripped.nrrd
The file doesn't exist. 
Filename = /Users/foxet/Documents/zhanghong/output/SkullStripping/P001_stx_stripped.nrrd

Run without any arguments to see command line options
Exception: Invalid segmentation parameter values

Traceback (most recent call last):
  File "/Users/foxet/Documents/zhanghong/output/PythonScripts/main_script.py", line 288, in <module>
    main(args)
  File "/Users/foxet/Documents/zhanghong/output/PythonScripts/main_script.py", line 121, in main
    BRAIN_MASK_base = os.path.splitext(os.path.basename(BRAIN_MASK))[0]
  File "/Users/foxet/fsl/lib/python3.10/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by styner** [comment]
The error shows that the output of the registration is missing, i.e. the registration failed. And then everything further down the workflow fails because of that missing registration output. 

If you look at the output files/folders, do you have a file called P001_stx.nrrd or P001_stx.nhdr?

You could try to first convert your file to .nrrd and see whether that helps.

Best
Martin

**Comment by foxet** [comment]
> The error shows that the output of the registration is missing, i.e. the registration failed. And then everything further down the workflow fails because of that missing registration output.
> 
> If you look at the output files/folders, do you have a file called P001_stx.nrrd or P001_stx.nhdr?
> 
> You could try to first convert your file to .nrrd and see whether that helps.
> 
> Best Martin



Hi Martin
Thanks for ur response.

I tried nrrd and nii, both failed and there is no P001_stx.nrrd or P001_stx.nhdr in the output directory.
could u please check my file?
[P001.nii.zip](https://github.com/NIRALUser/auto_EACSF/files/12148435/P001.nii.zip)



best wish
Lin
